services:
    mcp-server:
        ports:
            - "8080:8080"

    mcp-database-toolbox:
        ports:
            - "5000:5000"
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
        volumes:
          - ~/.config/gcloud:/root/.config/gcloud
        user: root

    data-ai-bot:
        environment:
          - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
          - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
          - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
          - OPENAI_API_KEY=${OPENAI_API_KEY}
          - OPENAI_BASE_URL=${OPENAI_BASE_URL}
          - OPENAI_MODEL_ID=${OPENAI_MODEL_ID}
