services:
    mcp-server:
        image: ghcr.io/de-code/py-conf-mcp_unstable:main-e113860d-20250430.0848
        environment:
            - CONFIG_FILE=/config/mcp-server.yaml
        volumes:
            - ./config/mcp-server.yaml:/config/mcp-server.yaml

    mcp-database-toolbox:
        image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.4.0
        volumes:
            - ./config/mcp-database-toolbox.yaml:/config/mcp-database-toolbox.yaml
        command: >
            --address 0.0.0.0
            --port 5000
            --tools-file /config/mcp-database-toolbox.yaml

    data-ai-bot:
        depends_on:
            - mcp-server
        build:
            context: .
        image: ${IMAGE_REPO}:${IMAGE_TAG}
        environment:
            - CONFIG_FILE=/config/docker-agent.yaml
        volumes:
            - ./config/docker-agent.yaml:/config/docker-agent.yaml
