toolDefinitions:
  fromPythonToolInstance:
    - name: get_joke
      module: data_ai_bot.tools.example.joke
      key: get_joke
  fromPythonToolClass:
    - name: get_docmap_by_manuscript_id
      module: data_ai_bot.tools.data_hub.docmap
      className: DocMapTool

agent:
  tools:
    - get_joke
    - get_docmap_by_manuscript_id
