toolDefinitions:
  fromPythonToolClass:
    - name: how_to_use_this_tool
      description: |-
        Explain to the user how to use this AI tool.
        This also summarised what this tool knows.
        Also provides some example prompts.
      module: data_ai_bot.tools.sources.static
      className: StaticContentTool
      initParameters:
        content: |-
          You can for example ask questions relating to individual DocMap by a manuscript id.

          Example prompts:
            - From the DocMap, who are the editors of 101859?
            - How many reviews does the DocMap of 101859 have?

    - name: get_zen_quote
      module: data_ai_bot.tools.sources.web_api
      className: WebApiTool
      initParameters:
        description: |-
          Retrieve a random inspirational zen quote as JSON.
        url: https://zenquotes.io/api/random

    - name: get_docmap_by_manuscript_id
      description: |-
        Fetches a DocMap as JSON from the Data Hub DocMaps API.
      module: data_ai_bot.tools.sources.web_api
      className: WebApiTool
      initParameters:
        inputs:
          manuscript_id:
            type: string
            description: 'The 5 or 6 digit eLife manuscript id'
            regex: '\d{5,6}'
        url: 'https://data-hub-api.elifesciences.org/enhanced-preprints/docmaps/v2/by-publisher/elife/get-by-manuscript-id'
        query_parameters:
          manuscript_id: '{{ manuscript_id }}'

    - name: search_elife_papers
      description: |-
        Search eLife papers and returns JSON. This also returns the total count.
      module: data_ai_bot.tools.sources.web_api
      className: WebApiTool
      initParameters:
        inputs:
          query:
            type: string
            description: 'The search query. Can be empty.'
          article_type:
            type: string
            description: |-
              The article type filter criteria or empty.
              Only use if specified by user.
              One of: correction,editorial,expression-concern,feature,insight,research-advance,research-article,research-communication,retraction,registered-report,replication-study,review-article,scientific-correspondence,short-report,tools-resources
          subject_area:
            type: string
            description: |-
              The subject area filter criteria or empty.
              Only use if specified by user.
              One of: biochemistry-chemical-biology,cancer-biology,cell-biology,chromosomes-gene-expression,computational-systems-biology,developmental-biology,ecology,epidemiology-global-health,evolutionary-biology,genetics-genomics,immunology-inflammation,medicine,microbiology-infectious-disease,neuroscience,physics-living-systems,plant-biology,stem-cells-regenerative-medicine,structural-biology-molecular-biophysics
          significance:
            type: string
            description: |-
              The minimum significance filter criteria or empty.
              Only use if specified by user.
              One of: landmark,fundamental,important,valuable,useful
          strength:
            type: string
            description: |-
              The minimum strength filter criteria or empty.
              Only use if specified by user.
              One of: exceptional,compelling,convincing,solid,incomplete,inadequate
          start_date:
            type: string
            description: 'The start date to filter by, in YYYY-MM-DD format.'
            regex: '\d{4}-\d{2}-\d{2}|'
          end_date:
            type: string
            description: 'The end date to filter by, in YYYY-MM-DD format.'
            regex: '\d{4}-\d{2}-\d{2}|'
        url: 'https://api.elifesciences.org/search'
        query_parameters:
          for: '{{ query }}'
          type[]: '{{ article_type }}'
          subject[]: '{{ subject_area }}'
          elifeAssessmentSignificance[]: '{{ significance }}'
          elifeAssessmentStrength[]: '{{ strength }}'
          'start-date': '{{ start_date }}'
          'end-date': '{{ end_date }}'

    - name: get_senior_editors
      description: |-
        Retrieves a list of senior editors along with their expertise.
        Returns JSON.
      module: data_ai_bot.tools.sources.bigquery
      className: BigQueryTool
      initParameters:
        project_name: elife-data-pipeline
        sql_query: |-
          SELECT
            Name,
            Keywords,
            Techniques,
            Subject_Areas,
            Research_Interests,
            Website_URL,
            Current_Availability,
            Role_Name
          FROM `elife-data-pipeline.prod.mv_Editorial_Public_Editor_Profile`
          WHERE Role_Name = 'Senior Editor'

toolCollectionDefinitions:
  fromMcp:
    - name: local_mcp
      url: 'http://localhost:8080/sse'

agent:
  systemPrompt: |-
    You are Data AI Bot.
    Ensure to answer accurately.
    Ask follow up question if unsure.
    The final answer should be formatted as simple Markdown (without unnecessary headings).
  tools:
    - get_docmap_by_manuscript_id
    - how_to_use_this_tool
    - get_zen_quote
    - search_elife_papers
    - get_senior_editors
  toolCollections:
    - local_mcp
